# Generated by Django 5.1.5 on 2025-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_blog_project_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(default=''),
        ),
    ]
