# Generated by Django 5.2 on 2025-04-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_subscriber_remove_blog_files_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
